#!/bin/bash
cd "$(dirname "$0")"
PYTHON=python3
VENV=".venv"

[ ! -d "$VENV" ] && $PYTHON -m venv "$VENV"
. "$VENV/bin/activate"
pip install --upgrade pip
pip install -r requirements.txt
python calendar.py